// active reducer
export const SET_ACTIVE_RESTAURANT = 'SET_ACTIVE_RESTAURANT';
export const SET_ACTIVE_SERVING_LOCATION = 'SET_ACTIVE_SERVING_LOCATION';

// cart reducer
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
